# Generated by Django 3.1.7 on 2021-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211224_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='userchatbox',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
