# Generated by Django 4.0.2 on 2022-04-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_student_alter_user_options_and_more'),
        ('message', '0003_auto_20211224_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='messages',
            field=models.ManyToManyField(related_name='chat_box', to='message.Message'),
        ),
    ]
