# Generated by Django 3.1.7 on 2021-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='seen',
            new_name='r_seen',
        ),
        migrations.AddField(
            model_name='message',
            name='s_seen',
            field=models.BooleanField(default=False),
        ),
    ]
