# Generated by Django 3.1.7 on 2021-11-23 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_auto_20211123_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='r_seen',
        ),
        migrations.RemoveField(
            model_name='message',
            name='s_seen',
        ),
        migrations.AddField(
            model_name='chatbox',
            name='unseen_messages',
            field=models.ManyToManyField(related_name='unseen_messages', to='message.Message'),
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
