# Generated by Django 3.1.7 on 2021-12-12 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20211123_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chats', models.ManyToManyField(related_name='thread', to='message.ChatBox')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Seen',
        ),
    ]
