# Generated by Django 3.1.7 on 2021-12-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20211212_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
