# Generated by Django 3.1.7 on 2021-12-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20211224_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
    ]
