# Generated by Django 3.1.7 on 2021-11-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='verification_code',
            field=models.CharField(default='no code', max_length=15),
            preserve_default=False,
        ),
    ]
