# Generated by Django 3.1.7 on 2021-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211209_1353'),
        ('pages', '0005_auto_20211210_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='files',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='page',
        ),
        migrations.AlterField(
            model_name='page',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='page', to='posts.Post'),
        ),
        migrations.DeleteModel(
            name='PageComment',
        ),
        migrations.DeleteModel(
            name='PagePost',
        ),
    ]
