# Generated by Django 3.1.7 on 2021-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211211_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci sed inventore facilis rem delectus debitis. Corrupti delectus, ex, similique recusandae fugit aliquam vitae aliquid magnam ullam illo quaerat incidunt quia.'),
        ),
    ]
