# Generated by Django 3.1.7 on 2021-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20211213_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
