# Generated by Django 3.1.7 on 2021-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_page_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
