# Generated by Django 4.0.2 on 2022-04-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20211217_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='page',
        ),
    ]
