# Generated by Django 4.0.2 on 2022-04-13 10:47

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211122_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Student Account',
                'verbose_name_plural': "Student Account's",
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Normal Account', 'verbose_name_plural': "Normal Account's"},
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, upload_to=accounts.models._upload_user_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models._upload_user_path),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, to='accounts.Student')),
            ],
            options={
                'verbose_name': 'Teacher Account',
                'verbose_name_plural': "Teacher Account's",
            },
        ),
    ]
