# Generated by Django 4.0.2 on 2022-04-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_student_alter_user_options_and_more'),
        ('institution', '0003_course_remove_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='tutors',
            field=models.ManyToManyField(blank=True, to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='contact',
            name='resipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='accounts.Contact'),
        ),
    ]
