# Generated by Django 4.0.2 on 2022-04-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='MainFolder',
            fields=[
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=True)),
                ('items', models.ManyToManyField(blank=True, to='Files.File')),
                ('subfolders', models.ManyToManyField(blank=True, to='Files.Folder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_folder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='items',
            field=models.ManyToManyField(blank=True, to='Files.File'),
        ),
        migrations.AddField(
            model_name='folder',
            name='subfolders',
            field=models.ManyToManyField(blank=True, to='Files.Folder'),
        ),
    ]
