# Generated by Django 3.1.7 on 2021-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='w_posts',
            field=models.ManyToManyField(blank=True, related_name='post_against_rule', to='posts.Post'),
        ),
    ]
