# Generated by Django 4.0.2 on 2022-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_group_post_related_to_story'),
        ('groups', '0005_auto_20211224_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='group', to='posts.Post'),
        ),
    ]
